apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache
  namespace: llm-ops
  labels:
    app: vllm
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: llm-ops-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
