apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  namespace: llm-ops
  labels:
    release: prom
    app: vllm
spec:
  selector:
    matchLabels:
      app: vllm
  namespaceSelector:
    matchNames:
      - llm-ops
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
